// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGgb1sfjYLb-KcBS-UDaaNBxnJ9ajypOA',
    appId: '1:923769485534:web:34cc2a15c68f01c738aa4f',
    messagingSenderId: '923769485534',
    projectId: 'simple-music-app-2ba36',
    authDomain: 'simple-music-app-2ba36.firebaseapp.com',
    storageBucket: 'simple-music-app-2ba36.appspot.com',
    measurementId: 'G-2FGFH47PSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOvMSetEJM-iV2TVH8bRCNH0_rlielGO0',
    appId: '1:923769485534:android:dc245404ac3f869638aa4f',
    messagingSenderId: '923769485534',
    projectId: 'simple-music-app-2ba36',
    storageBucket: 'simple-music-app-2ba36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvcERpYZeUqDiGl5GklRjwRjjRm01rS34',
    appId: '1:923769485534:ios:1c69a88d15404a2f38aa4f',
    messagingSenderId: '923769485534',
    projectId: 'simple-music-app-2ba36',
    storageBucket: 'simple-music-app-2ba36.appspot.com',
    iosClientId: '923769485534-65ipuq9hm84oal6ut0vbiqvrbcbs3aer.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvcERpYZeUqDiGl5GklRjwRjjRm01rS34',
    appId: '1:923769485534:ios:1c69a88d15404a2f38aa4f',
    messagingSenderId: '923769485534',
    projectId: 'simple-music-app-2ba36',
    storageBucket: 'simple-music-app-2ba36.appspot.com',
    iosClientId: '923769485534-65ipuq9hm84oal6ut0vbiqvrbcbs3aer.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMusicApp',
  );
}
